### ISSUE TITLE
关于 Client 部分，我能否自己部署

### ISSUE THREAD

**Issue by zhengxs2018** [soulteary/docker-chatgpt#1]
使用我自己的 api key，主要是自己用用，我试了下你的代码，魔改后可以正常运行，速度真的快 👍。

虽然我想白嫖，但如果只是允许我是使用目前 docker 镜像也可以。

**Comment by soulteary** [comment]
正准备回复，看到你自己关闭了 issue  @zhengxs2018 


出于许多原因，client 不适合完全公开，或许仅提供 docker binary 已经足够了。

关于隐私顾虑，在项目中已更新，你可以通过任何手段限制这个程序，让它只能访问开源的 backend ，这不会影响它的运行，因为它除了 backend 依赖之外，没有其他的依赖了。 :)


----


For many reasons, the client is not suitable for full disclosure, perhaps only providing the docker binary is enough.

Regarding privacy concerns, it has been updated in the project. You can restrict this program by any means so that it can only access the open source backend, which will not affect its operation, because it has no other dependencies except the backend dependency. :)

**Comment by zhengxs2018** [comment]
我能理解，所以我关闭了，哈哈哈，多谢回复
