### ISSUE TITLE
Where is the source code of web-client?

### ISSUE THREAD

**Issue by gitrc** [soulteary/docker-chatgpt#7]
I am interested in the origins of the source code for 'web-client'.  Could you please link to it?  Also, what is the reason for the packer on web-client, to save space?  Thanks!

**Comment by soulteary** [comment]
ref https://github.com/soulteary/docker-chatgpt/issues/1#issuecomment-1543811248

yes, just use upx for better size, save the spaces.

**Comment by tirranaa** [comment]
I did liked the little very light, the two compiled binary files "web-client" and "sparrow" in the two containers, due to the small sizes, but hated the errors into the browser inspection section and after network inspection and further binary code compilers i determined the source code original is based on "[](https://github.com/mckaywrigley/chatbot-ui)", I loved the minimalistic design of the app, but hated the closed hidden source code. So after further investigation, into it, I found the network activity of the containers, scanned the errors and comunications and decompiled the sources to realise, it was stripped down version with attempt to hide, it's original source code edited, stripped down and closed into Two Binaries... If it was open source, was gonna be much better, for the community ! Anyways, good job.

**Comment by tirranaa** [comment]
And, I say, good job, considering, what a mess of a code, you had to edit, to get there, from here...
![edit](https://github.com/soulteary/docker-chatgpt/assets/62551449/3fa8a802-e028-473d-b693-61ce3f873129)
to here....
![edit2](https://github.com/soulteary/docker-chatgpt/assets/62551449/6a32483d-55b4-45e3-b3c0-cb37a012ac55)
I only, investigated it, because it was binary compiles... was never gonna, if it was just source code, that everyone loves, to read...
